### PR TITLE
use atom shell as wrapper

### PR DESCRIPTION
**Pull request by bsudekum**
This PR wraps TileMill in atom-shell as outlined in https://github.com/mapbox/tilemill/issues/2467

### Notable Changes:
- Travis is running both osx and linux builds
 - because of this, postgres/gis needs to be manually installed, addons don't work
 - [Mason now installs postgres/gis](https://github.com/mapbox/tilemill/blob/atom/scripts/install-postgres.sh)
- Some modules were confused whether the code was running in the browser or on the server. [It is now manually set](https://github.com/mapbox/tilemill/blob/atom-shell/templates/App._#L9-L19)
- Clicking an `<a>` tag no longer automatically downloads a file with atom. Because of this, it needs to be [done manually](https://github.com/mapbox/tilemill/blob/atom-shell/views/App.bones#L268-L314)
- [`updateVersion`](https://github.com/mapbox/tilemill/blob/atom-shell/servers/App.bones#L136-L149) now checks again a `latest` file on s3 that is generated during packaging process.
- there are no longer background updates on any platform

### Known issues
- [ ] On linux, the app icon is the default atom icon
- [x] On windows, the app icon is the default atom icon
- [x] On linux, sometimes child processes do not stop
- [x] application logging is not working

### Next Steps
- [ ] review from @springmeyer @yhahn
- [x] more platform testing
- [ ] public beta? Simple tweet
- [ ] Move over s3 build destination to tilemill/latest
- [ ] official release

### CODE REVIEW

**Comment by bsudekum** [comment]
> On linux, sometimes child processes do not stop

Edit, this is actually true on all platforms. Not sure what the issue here is, child processes at one point were properly exiting. Investigating.

**Comment by bsudekum** [comment]
It appears it is only `tilemill-tile` and `tilemill-ui` that continue to run. The `atom` and `tilemill` process are properly killed.

**Comment by bsudekum** [comment]
I think there could be some race condition here. When exiting via `ctrl + c`, everything is properly killed. However, when exiting via `ctrl + q` which is an atom-shell process, tilemill-ui and tilemill-tile still are alive.

**Comment by bsudekum** [comment]
> On linux, sometimes child processes do not stop

I was able to fix this by specify the exit code `SIGINT` and listening on the process `SIGINT`. `process.on('exit')` was not specific enough. See https://github.com/mapbox/tilemill/commit/c96cb3cd7563224e8a02a168d01e7987fdc288b5

**Comment by palmerj** [comment]
On Mac 10.10.3 I get the following error on start-up:

I encountered an error:
```
[tilemill] events.js:72
[tilemill]         throw er; // Unhandled 'error' event
[tilemill]               ^
[tilemill] Error: listen EADDRINUSE
[tilemill]     at errnoException (net.js:904:11)
[tilemill]     at Server._listen2 (net.js:1042:14)
[tilemill]     at listen (net.js:1064:10)
[tilemill]     at Server.listen (net.js:1138:5)
[tilemill]     at server.start (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/servers/Tile.bones:18:14)
[tilemill]     at command.initialize (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/commands/tile.bones:24:26)
[tilemill]     at null.<anonymous> (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/bones/server/command.js:8:14)
[tilemill]     at command.bootstrap (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/commands/tile.bones:18:5)
[tilemill]     at Command (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/bones/server/command.js:7:10)
[tilemill]     at new child (/Users/jpalmer/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/backbone/backbone.js:964:41)

**Comment by springmeyer** [comment]
@palmerj - The `EADDRINUSE` means something else is already running on port 20009. Because that is a pretty unique port it is likely another instance of TileMill or a runaway process. You should be able to fix this by restarting your machine or tracking down the process in Activity Monitor as per https://www.mapbox.com/tilemill/docs/mac-troubleshooting/#check-for-and-stop-any-runaway-processes. This should not be happening, so let me know if you experience it again and what you think might have lead up to the problem.

**Comment by palmerj** [comment]
@springmeyer - thanks that was the problem. I will report if I see this again.

**Comment by springmeyer** [comment]
@palmerj - great, thank you. Do let me know what you find: runaway processes like that are the thing @bsudekum encountered in this port and the main thing holding up this merging and becoming an official release. So any insight you can provide would be great.

**Comment by willwhite** [comment]
Looks like the appveyor build is new and failing on this branch. @springmeyer does anything jump out to you about the failure above?

**Comment by palmerj** [comment]
Is there still a plan to release one more tilemill release?

**Comment by tmcw** [comment]
Closing as stale, anyone is free to work from the branch to create a new PR if they wish to take the initiative.

**Pull request closed without merging**
