### PR TITLE
Add Delete All button to Exports List dialog

### PR DESCRIPTION
**Pull request by csytsma**
Fixes issue #2704 

Test to confirm Delete All button shows up in the upper-right corner.
Test that it deletes all Exports. Warning, this will delete ALL exports for every project.
TODO: Could try to ask if the user wants to delete ALL or only for current project. However, current Modal window only allows Yes/No answers, no multiple choice custom answers. So this would take some work.

### CODE REVIEW

**Comment by tpotter7** [comment]
I put in "Tim Export" as a file name and got this error: "Error: String does not match pattern (filename)". I figured out that the problem was the space and saved successfully with "Tim_Export" as the file name. But, the error message could be made more clear.

**Comment by tpotter7** [comment]
This is a nice to have, but is it possible to have the search look in both the filename as well as the description?

**Comment by csytsma** [comment]
Closing PR, replacing with a new PR.

**Comment by csytsma** [comment]
Done.

**Pull request closed without merging**
